automationbroker/apb

- cmd/bundle.go
Before:
```
specs: [0xc42064e210 0xc42064e0b0 0xc42065c000]hello-world-db-apb - docker.io/jmrodri/hello-world-db-apb:latest                                                                                                   
postgresql-apb - docker.io/jmrodri/postgresql-apb:latest
mediawiki123-apb - docker.io/jmrodri/mediawiki123-apb:latest
```
After:
```
specs: [0xc420626000 0xc42055e0b0 0xc42055e2c0]
mediawiki123-apb - docker.io/jmrodri/mediawiki123-apb:latest
hello-world-db-apb - docker.io/jmrodri/hello-world-db-apb:latest
postgresql-apb - docker.io/jmrodri/postgresql-apb:latest
```
> add newline to specs line

- cmd/binding.go
- cmd/bundle.go
- cmd/exec.go
- cmd/root.go
- Set default logging level to "info" instead of "warning"
- Switch to fmt.Print[f,ln] instead of log.Print[f,ln] for regular command output
- Remove timestamps in `[0000]` format from logrus output
> Use fmt.Print for regular output, remove logrus timestamps

- cmd/bundle.go
- cmd/registry.go
- util/table_printer.go
Output of `sbcli bundle list` now looks like this:
```
BUNDLE                 |  IMAGE
---------------------  |  -------------------------------------------------------------------
es-apb                 |  docker.io/ansibleplaybookbundle/es-apb:latest
hello-world-apb        |  docker.io/ansibleplaybookbundle/hello-world-apb:latest
vnc-desktop-apb        |  docker.io/ansibleplaybookbundle/vnc-desktop-apb:latest
kibana-apb             |  docker.io/ansibleplaybookbundle/kibana-apb:latest
pyzip-demo-apb         |  docker.io/ansibleplaybookbundle/pyzip-demo-apb:latest
mssql-remote-apb       |  docker.io/ansibleplaybookbundle/mssql-remote-apb:latest
mongodb-apb            |  docker.io/ansibleplaybookbundle/mongodb-apb:latest
import-vm-disk-apb     | …
```
> Uniformly size columns + add labels to spec list output.

- cmd/completion.go
- Add `bash` completion
- Add `zsh` completion
To use either of these completion features, run the appropriate command for your shell:
```
source <(sbcli completion bash)
source <(sbcli completion zsh)
```
> Add kubectl-esque completion for bash and zsh.

- cmd/bundle.go
- cmd/completion.go
- cmd/registry.go
- cmd/root.go
- util/table_printer.go
- Move specs to reside under registries in the config file.
- Add "REGISTRY" header to `sbcli list`
- `sbcli list` will automatically retrieve new specs for any empty registries found in the config file
- Add some printing functionality
> Specs under registries

- util/table_printer.go
Simple fix to print appropriately sized output columns even when no column data is available to print.
From this:
```
[dwhatley@precision-t sbcli]$ ./sbcli bundle list
BUNDLE      IMAGE      REGISTRY  
-+-   -+-   
```
To this:
```
[dwhatley@precision-t sbcli]$ ./sbcli bundle  list
BUNDLE     IMAGE     REGISTRY  
------ -+- ----- -+- -------- 
```
> Size columns appropriately even when no column data is present.

- pkg/runner/runner.go
- Add the parameter description to the prompt line when it exists
- Gives the user more context about what they should enter as a param value
> Add description to parameter prompt.

- cmd/bundle.go
`sbcli bundle provision awx-apb -n <your-namespace>`
instead of 
`sbcli bundle provision awx-apb -p <your-namespace>`
> Change -p option to -n to match kubectl and oc usage pattern.

- cmd/binding.go
- cmd/bundle.go
- pkg/runner/runner.go
- Add ability to specify registry when performing `provision`/`deprovision`
- Fix typo in `binding` command description (looks like it was previously copied from the `registry` command desc)
> Add registry flags to "bundle" commands

- cmd/bundle.go
- cmd/registry.go
- Exported `ListImages` function from bundle.go to be used by registry.go
- Moved `ListImages` to the top of bundle.go (felt right to me, but open to correction if this goes against convention)
> Update cached bundle spec metadata when a new registry is added.

- cmd/bundle.go
Change `sbcli bundle prepare` output to include OpenShift build commands:
```
[dwhatley@precision-t ST2]$ sbcli bundle prepare
Wrote b64 encoded [apb.yml] to [Dockerfile]
Create a buildconfig:
oc new-build . --to <bundle-name>
Start a build:
oc start-build --from-dir . <bundle-name>
```
Spoke with @dymurray about eventually hooking into the OpenShift rest calls so that we can provide an actual `build` command that creates a buildconfig and triggers a build automatically. These commands _should_ allow users to build bundles without root privs in the meantime.
> Add OpenShift build instructions to "bundle prepare"

- cmd/bundle.go
- pkg/util/kubeconfig.go
This will now attempt to load the namespace from the current context in the kubeconfig.
> Remove requirement to supply namespace

- cmd/bundle.go
- pkg/runner/runner.go
Added `-f` and `--follow` options to provision and deprovision so that you can automatically view the logs that result from the bundle run.
Addresses https://github.com/automationbroker/apb/issues/46
```
[dwhatley@precision-t apb]$ apb bundle provision mediawiki-apb -n foobar --follow
Found bundle [mediawiki-apb] in registry [docker]
Plan: default
Enter value for parameter [mediawiki_db_schema], default: [mediawiki]: 
[...]
INFO Creating RoleBinding bundle-867f2119-bf84-47d5-86ec-776163c21704 
INFO Successfully created apb sandbox: [ bundle-867f2119-bf84-47d5-86ec-776163c21704 ], with edit permissions in namespace foobar 
INFO Running post create sandbox functions if defined. 
Successfully created pod [bundle-867f2119-bf84-47d5-86ec-776163c21704] to provision [mediawiki-apb] in namespace …
```
> Add support for viewing bundle logs for action.

- cmd/registry.go
* Update `sbcli registry add` to accept `type` as an input argument with flags to override the config defaults
* Update `sbcli registry remove` to accept `name` as an argument with no flags
* Adds ability to specify namespaces and whitelists as comma-separated list
What is left to be done:
* Revisit this once the v2 adapter work is merged into bundle-lib to supply another smart default config
> Make registry subcommand experience better

- cmd/broker.go
- cmd/bundle.go
- cmd/helpers.go
- Provide top-level commands like in old APB tool
- Hide top-level commands so that help-text is clean 
- Add stubs for `apb init`, `apb build`, `apb push` with deprecation messages
Now you have the *option* of typing out the `bundle` in `apb bundle provision` which I think is great ;)
> Match old apb commands

- cmd/broker.go
- cmd/catalog.go
- cmd/root.go
- pkg/util/kubeconfig.go
Includes small error check for current-context gathering.
Note: I would like to come back to this to use the dynamic go client to grab these resources but this is clean for now.
> Add support for `apb catalog relist`

- apb.spec
Downstream we have golang 1.10 in the buildroot. In 1.10 on Fedora the go macros were broken out into a separate package and golang has a dependency on this package (go-srpm-macros). Downstream in our buildroot this package does not exist and golang has no such dependency so we need to define/remove macros ourselves to get this built.
> Remove go compiler macro

- cmd/broker.go
- cmd/bundle.go
- cmd/catalog.go
- cmd/completion.go
- cmd/config.go
- cmd/registry.go
- cmd/root.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/runner/runner.go
- pkg/util/kubeconfig.go
`apb config` provides the ability to specify configuration variables for interaction with the Automation Broker. This should ease user issues when name changes occur. 
- Add `apb config` command
- Adapt `broker bootstrap/catalog` and `catalog relist` to use configuration values
- Move config files (registries.json and new defaults.json) into ~/.apb dir
Example of keeping all defaults but changing name of clusterservicebroker
```
derek $ >> apb config
Broker namespace [default: openshift-automation-service-broker]: 
Broker resource URL [default: /apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers/]: 
Broker route name [default: openshift-automation-service-broker]: 
clusterservicebroker [default: openshift-automation-service-broker]: ansible-service-broker
Saving new …
```
> Add `apb config` cmd for configuring broker/catalog interaction vars

- cmd/registry.go
Only thing I am unsure about is the default org... I am not aware of any quay registry orgs that have APBs.
I think it's fine to leave it blank and expect a user to input that.
Fixes #98
> Add quay registry adapter

- cmd/bundle.go
- pkg/runner/runner.go
In the past we were checking the contents of a file on the container to check if the APB succeeded in the test. This seemed incredibly pointless to me so instead I have talked with @djzager and determined we should simply judge a test status on whether or not the container is in a failed state or a succeeded state. This makes the workflow much simpler and now if a person wants to write a set of unit tests they can simply run the `fail` module in Ansible to signify a failed test which will put the pod in an error state.
> Bug 1595153 - Add support for apb test that works in and out of cluster

- cmd/broker.go
- docs/apb_cli.md
- pkg/runner/runner.go
The APBs will set their own defaults for in_cluster, there is no reason to hardcode them. We also really shouldn't be hardcoding the service_instance IDs. I will follow up with that.
> Bug 1620042 - do not harcode in_cluster var & update docs

- cmd/broker.go
- cmd/config.go
- pkg/config/config.go
- pkg/config/types.go
Testing from a 3.9 cluster
```
[dymurray@pups apb]$ apb config                                         
Broker namespace [default: openshift-automation-service-broker]:        
Broker resource URL [default: /apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers/]: ^C
[dymurray@pups apb]$ apb config                                         
Broker namespace [default: openshift-automation-service-broker]: ansible-service-broker
Broker resource URL [default: /apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers/]:
Broker route name [default: broker]: asb                               
clusterservicebroker resource name [default: openshift-automation-service-broker]: ansible-service-broker
Broker route suffix [default: osb]:                                     
Saving new …
```
> Add broker route suffix as a config option

- cmd/binding.go
This fixes binding failures from `mysql-apb`. This is because MySQL is setting `DB_PORT` to `3306` instead of `"3306"` like we see with PostgreSQL.
Instead of forcing all this data to be a string we should be more defensive and simply marshal the data to get a byte array. This prevents unwanted panics.
> Bug 1626986 - Marshal ext creds instead of assuming interface type

- cmd/bundle.go
- cmd/root.go
- pkg/util/kubeconfig.go
allow users to modify the default `$HOME/.kube/cofing` via the `--kubeconfig` or the `KUBECONFIG` environment variable
> Bug 1640050 - add `--kubeconfig` and `KUBECONFIG env` support

- cmd/bundle.go
- cmd/root.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/runner/runner.go
Can now provision postgresql twice in the same namespace:
```
[dymurray@dymurray-desktop apb]$ oc get pods                          
NAME                                                      READY     STATUS      RESTARTS   AGE                                               
bundle-27df4f0b-9452-45ff-aad3-52b33e399118               0/1       Completed   0          23s                                               
bundle-fdf081f0-e609-4b70-883d-0c624b0800f9               0/1       Completed   0          3m                                                
postgresql-27df4f0b-9452-45ff-aad3-52b33e399118-1-n49xl   1/1       Running     0          11s                                               
postgresql-fdf081f0-e609-4b70-883d-0c624b0800f9-1-6zkls   1/1       Running     0          3m …
```
> Bug 1625751 - Use uuids for service_instance labels

- .gitignore
- Makefile
Run `make build-all` and get both Linux and Mac OS/X executables. They will be named: `apb-darwin-amd64 and apb-linux-amd64`.
> add cross compilation for Mac OS/X.

- cmd/root.go
[bz1640050](https://bugzilla.redhat.com/show_bug.cgi?id=1640050)
Depends on [bundle-lib PR](https://github.com/automationbroker/bundle-lib/pull/181)
> set KUBECONFIG env for all commands
